### ISSUE TITLE
unhandled exception on Get ERP/ICE/BAQ services

### ISSUE THREAD

**Issue by bmanners** [EdWelsh/EpicorRESTClientGenerator#1]
If the URL for the services is not valid and the user clicks Get Services button an exception is thrown. 

I have added a try/catches to fix this but not sure how to upload a commit? I assume i don't push it as you wont be able to review / reject it if its not correct or needs more work..

**Comment by EdWelsh** [comment]
create a pull request and I can take a look there, thank you!

**Comment by EdWelsh** [comment]
I went ahead and added the new branch, created a pull request and applied the change for exceptions. If you find anymore go ahead and commit to the exception branch and create a new pull request

**Comment by bmanners** [comment]
Ed, found another :-) tried to commit to the exception branch but got a permission denied error. Its quite possible I am doing something wrong as i am new to Github...

the IsValidURL will throw an exception in the catch block when ex.response is null. That happens for an invalid URL  eg if i just leave the default url and click the check button.

**Comment by EdWelsh** [comment]
I went ahead and added some more exception to include all cases, thank you for keeping me on my toes. I really should go through and ensure this is production ready. :)
