### ISSUE TITLE
Missing null checking in GenerateCode method

### ISSUE THREAD

**Issue by asjJRAutomation** [EdWelsh/EpicorRESTClientGenerator#3]
Runtime Binding exception on line 81 of Service.cs, resulting from null reference when accessing non-existent JProperty "post".

Log file and proposed fix attached.
[Attach.zip](https://github.com/EdWelsh/EpicorRESTClientGenerator/files/1205294/Attach.zip)

**Comment by EdWelsh** [comment]
I submitted your suggested code changes :) 

You can in the future clone and then make a pull request with your fixes. If they work then I will push them into the master branch
