### ISSUE TITLE
AddReference does not support Visual Studio 2017

### ISSUE THREAD

**Issue by asjJRAutomation** [EdWelsh/EpicorRESTClientGenerator#4]
Microsoft.Build.Exceptions.InvalidProjectFileException when attempting to load Visual Studio 2017 project in AddReference method.

Providing "14.0" version parameter in LoadProject method solves the issue, forcing to treat project as VS2015.

Log file attached.
[Attach.zip](https://github.com/EdWelsh/EpicorRESTClientGenerator/files/1205306/Attach.zip)

**Comment by EdWelsh** [comment]
I was not planning on supporting VS2017, I feel with that upgrade I should then focus on .net core and as the rest of the world is not there yet I am reluctant to do so, however your fix is easy so I will put it into the project :)
